//used to detemine multiplier for liked/disliked categories - defaults at 1
var topCategories = [
  {name: 'American (New)', multiplier: 1},
  {name: 'American (Traditional)', multiplier: 1},
  {name: 'Asian Fusion', multiplier: 1},
  {name: 'Barbeque', multiplier: 1},
  {name: 'Breakfast & Brunch', multiplier: 1},
  {name: 'Buffets', multiplier: 1},
  {name: 'Burgers', multiplier: 1},
  {name: 'Cafes', multiplier: 1},
  {name: 'Chinese', multiplier: 1},
  {name: 'Fast Food', multiplier: 1},
  {name: 'French', multiplier: 1},
  {name: 'Gluten-Free', multiplier: 1},
  {name: 'Greek', multiplier: 1},
  {name: 'Indian', multiplier: 1},
  {name: 'Italian', multiplier: 1},
  {name: 'Japanese', multiplier: 1},
  {name: 'Kosher', multiplier: 1},
  {name: 'Mediterranean', multiplier: 1},
  {name: 'Mexican', multiplier: 1},
  {name: 'Middle Eastern', multiplier: 1},
  {name: 'Pizza', multiplier: 1},
  {name: 'Ramen', multiplier: 1},
  {name: 'Sandwiches', multiplier: 1},
  {name: 'Seafood', multiplier: 1},
  {name: 'Soul Food', multiplier: 1},
  {name: 'Soup', multiplier: 1},
  {name: 'Southern', multiplier: 1},
  {name: 'Steakhouses', multiplier: 1},
  {name: 'Sushi Bars', multiplier: 1},
  {name: 'Tapas/Small Plates', multiplier: 1},
  {name: 'Thai', multiplier: 1},
  {name: 'Vegan', multiplier: 1},
  {name: 'Vegetarian', multiplier: 1}
];

module.exports = topCategories;
